Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [16]:
NAME = "MD Sakib"
COLLABORATORS = "MD Sakib"

---

# Assignment 2 — K-Nearest Neighbors (KNN) Algorithm (30 Marks)
Please read all instructions carefully before starting this assignment.

General Instructions:
- Use the file student_knn_dataset.csv provided in this assignment folder.
- Do not rename or modify the CSV file or its contents.
- Each question specifies exact variable names you must use. These names are required for automatic grading.
- Incorrect or misspelled variable names may cause your answers to fail the autograder.
- You cannot edit the instruction or setup cells.
- Write your code only inside the cells marked as “Your Code Here.”
- Do not modify or delete any cell marked as “DO NOT WRITE ANYTHING HERE.”
- Replace the line "raise NotImplementedError()" with your code in each question cell.  
- Run all cells from top to bottom before submission.
- Ensure that all code executes without errors and all required outputs appear correctly.
- Save your notebook after completing all tasks.
- Submit only the .ipynb file as your final solution.
- Failure to follow these instructions may result in deduction of marks.

File Naming Convention:
- Your notebook must be named as:
name_serialNumber.ipynb
- Example:
If your name is Rahul Kumar Sharma and your serial number is 30, then your file name should be:
rahul_kumar_sharma_30.ipynb

### Load Dataset (Already Implemented)

The dataset `student_knn_dataset.csv` is provided to you.  
The following cell loads the dataset into a dataframe named `df` and imports
all necessary libraries required for this assignment.

Please run the cell below before attempting any other question.
Do not modify or delete this cell.


In [17]:
# DO NOT WRITE ANYTHING HERE

# Import required libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from collections import Counter
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("student_knn_dataset.csv")

print("Environment setup complete.")
print("Dataset loaded successfully.")
print("Shape of dataframe:", df.shape)

df.head()  # Show first few rows


Environment setup complete.
Dataset loaded successfully.
Shape of dataframe: (1000, 6)


,Age,Salary,Experience,Study_Hours,Score,Class_Label
0,56,146108,5,9.72,100.00,High
1,46,34382,13,3.00,53.60,Medium
2,32,104291,17,3.08,61.62,Medium
3,25,121195,11,4.99,65.90,Medium
4,38,154828,10,9.85,100.00,High


### Q1: Apply Feature Scaling

Use StandardScaler to scale the feature columns:
['Age', 'Salary', 'Experience', 'Study_Hours']

Store output in a numpy array named:
scaled_features


In [18]:
features = ['Age', 'Salary', 'Experience', 'Study_Hours']
scaled_features = StandardScaler().fit_transform(df[features])
print(scaled_features)

[[ 1.41659231  0.63427989 -0.82721997  1.59390286]
 [ 0.59561734 -1.51272669  0.46430223 -0.87946702]
 [-0.55374762 -0.16930544  1.11006333 -0.85002214]
 ...
 [ 0.59561734 -0.88939414 -1.15010052  0.69951464]
 [-1.12843009 -0.37148448  0.14142168  1.28105101]
 [-1.37472258  1.24786956  0.30286196  0.7584044 ]]


In [19]:
# DO NOT WRITE ANYTHING HERE

### Q2: Train-Test Split

Split scaled_features and Class_Label into:
- `X_train`, `X_test`
- `y_train`, `y_test`

Use an 80/20 split manually (not sklearn).


In [20]:
# YOUR CODE HERE
splitPoint = int(0.8 * len(df))

X_train = scaled_features[:splitPoint]
X_test = scaled_features[splitPoint:]

y_train = df['Class_Label'][:splitPoint]
y_test = df['Class_Label'][splitPoint:]

# df.info()

In [21]:
# DO NOT WRITE ANYTHING HERE

### Q3: Euclidean Distance

Write a function `calculate_euclidean_distance(a, b)`
which returns the Euclidean distance between two numpy vectors


In [22]:
# YOUR CODE HERE
def calculate_euclidean_distance(a, b):
    return np.sqrt(np.sum((a-b)**2))

In [23]:
# DO NOT WRITE ANYTHING HERE

### Q4: Single Prediction Using KNN

Write a function `knn_predict_single(test_point, X_train, y_train, K=5)` that:
1. Computes distances between test_point and all training samples
2. Finds the K nearest neighbors
3. Returns the predicted class label based on majority vote


In [24]:
# YOUR CODE HERE
def knn_predict_single(test_point, X_train, y_train, K=5):
    distances = []
    k_nearest_labels = []
    for i in range(len(X_train)):
        dist = calculate_euclidean_distance(test_point, X_train[i])
        distances.append((dist, y_train.iloc[i]))
    
    distances.sort(key=lambda x: x[0])

    for i in range(K):
        k_nearest_labels.append(distances[i][1])
    
    most_common = Counter(k_nearest_labels).most_common(1)
    return most_common[0][0]

In [25]:
# DO NOT WRITE ANYTHING HERE

### Q5: Full Test Prediction

Use `knn_predict_single` to generate predictions for entire X_test.
Store predictions list in variable: predictions


In [26]:
# YOUR CODE HERE
predictions = []
for test_row in X_test:
    result = knn_predict_single(test_row, X_train, y_train, K=5)
    predictions.append(result)

print(predictions)

['Medium', 'Low', 'Low', 'Low', 'Low', 'Medium', 'High', 'Low', 'High', 'Low', 'High', 'High', 'Medium', 'Low', 'Medium', 'Low', 'High', 'Low', 'High', 'Low', 'High', 'Medium', 'High', 'Low', 'High', 'Medium', 'High', 'Medium', 'High', 'Low', 'High', 'High', 'High', 'Medium', 'Medium', 'High', 'Low', 'High', 'High', 'Medium', 'Low', 'High', 'High', 'Low', 'High', 'Low', 'High', 'Low', 'Low', 'High', 'Medium', 'Medium', 'Low', 'High', 'High', 'Medium', 'Low', 'High', 'Medium', 'Medium', 'Low', 'High', 'Medium', 'Medium', 'Low', 'High', 'Medium', 'High', 'Medium', 'Low', 'High', 'Medium', 'High', 'High', 'High', 'Low', 'High', 'Medium', 'High', 'High', 'High', 'Medium', 'High', 'Low', 'High', 'Medium', 'Medium', 'High', 'High', 'Low', 'Medium', 'Medium', 'Medium', 'Low', 'Low', 'Medium', 'High', 'Low', 'Low', 'High', 'Low', 'Medium', 'High', 'High', 'High', 'High', 'High', 'Medium', 'High', 'Low', 'High', 'Medium', 'Medium', 'Medium', 'High', 'Low', 'High', 'High', 'Low', 'High', 'High',

In [27]:
# DO NOT WRITE ANYTHING HERE

### Q6: Accuracy Score

Compute accuracy and store in variable `accuracy_score`


In [28]:
# YOUR CODE HERE
correct_count = 0
total_count = len(y_test)

y_test_list = y_test.tolist()

for i in range(total_count):
    if predictions[i] == y_test_list[i]:
        correct_count += 1

accuracy_score = correct_count / total_count
print("The accuracy of the model is:", accuracy_score)

The accuracy of the model is: 0.86


In [29]:
# DO NOT WRITE ANYTHING HERE

### End of Assignment

Please make sure all your code cells have been executed and outputs are visible before submitting.
